### ISSUE TITLE
Способ для youtube music

### ISSUE THREAD

**Issue by Skro11-ru** [KrimsonKing1337/add-tracks-to-spotify#6]
let ArrayTracks = [];
let tempArrayTracks = [...document.querySelectorAll(".flex-columns")];
tempArrayTracks.forEach((trackItem) => {
  let trackName = "";
  let trackAuthor = "";
  const tempTrackName = trackItem.querySelector("yt-formatted-string");
  if (tempTrackName) {
    trackName = tempTrackName.getAttribute("title");
  }
  const tempTrackAuthor = trackItem.querySelector(
    ".secondary-flex-columns>yt-formatted-string"
  );
  if (tempTrackAuthor) {
    trackAuthor = tempTrackAuthor.getAttribute("title");
  }
  const fullNameTrack = trackAuthor + " - " + trackName;
  ArrayTracks.push(fullNameTrack);
});
console.log(ArrayTracks.join("\n"));

**Comment by KrimsonKing1337** [comment]
спасибо, добавлю!

**Comment by KrimsonKing1337** [comment]
добавил
